sudo: required
services:
    - docker
before_install:
    - docker build -t anastayaa/react-test -f ./client/Dockerfile ./client
script:
    - docker run anastayaa/react-test npm test -- --coverage
after_success:
    - docker build -t anastayaa/multi-client -f ./client/Dockerfile.prod  ./client
    - docker build -t anastayaa/multi-nginx -f ./nginx/Dockerfile.prod  ./nginx
    - docker build -t anastayaa/multi-server -f ./server/Dockerfile.prod  ./server
    - docker build -t anastayaa/multi-worker -f ./worker/Dockerfile.prod  ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push anastayaa/multi-client
    - docker push anastayaa/multi-nginx
    - docker push anastayaa/multi-server
    - docker push anastayaa/multi-worker