version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
  redis:
    image: redis:latest
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - PGPASSWORD=postgres_password
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./worker:/app
